name: CI
on: push
jobs:
  main:
    name: Check, lint & test
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.2.0'

      - name: Install R package dependencies
        uses: r-lib/actions/setup-r-dependencies@v2

      - name: R CMD check
        if: always()
        uses: r-lib/actions/check-r-package@v2
        with:
          error-on: '"note"'
        env:
          _R_CHECK_LICENSE_: 'FALSE' # We are using a proprietary license.

      - name: Lint
        if: always()
        shell: Rscript {0}
        run: |
          lints <- lintr::lint_package()
          for (lint in lints) print(lint)
          quit(status = length(lints) > 0)
